# Generated by Django 5.0.8 on 2024-08-11 20:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content_file',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='No content available'),
        ),
    ]
