# Generated by Django 5.0.8 on 2024-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
